Testsuite: logging.LoggerTest
Tests run: 4, Failures: 3, Errors: 0, Time elapsed: 0.055 sec

Testcase: testAllHandlersNeedToBeCalled took 0.015 sec
	FAILED

  Unexpected method call write("
Error", 30):
    write("Error", 30): expected: 1, actual: 0
junit.framework.AssertionFailedError: 
  Unexpected method call write("
Error", 30):
    write("Error", 30): expected: 1, actual: 0
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:29)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:45)
	at $Proxy6.write(Unknown Source)
	at logging.Log._filter(Log.java:91)
	at logging.Log.error(Log.java:64)
	at logging.LoggerTest.testAllHandlersNeedToBeCalled(LoggerTest.java:56)

Testcase: testHandlerFiltering1 took 0.002 sec
	FAILED

  Unexpected method call write("
Error", 30):
    write("Error", 30): expected: 1, actual: 0
junit.framework.AssertionFailedError: 
  Unexpected method call write("
Error", 30):
    write("Error", 30): expected: 1, actual: 0
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:29)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:45)
	at $Proxy6.write(Unknown Source)
	at logging.Log._filter(Log.java:91)
	at logging.Log.error(Log.java:64)
	at logging.LoggerTest.testHandlerFiltering1(LoggerTest.java:75)

Testcase: testLoggerFiltering2 took 0.001 sec
	FAILED

  Unexpected method call write("
Error", 10):
    write("Error", 10): expected: 1, actual: 0
junit.framework.AssertionFailedError: 
  Unexpected method call write("
Error", 10):
    write("Error", 10): expected: 1, actual: 0
	at org.easymock.internal.MockInvocationHandler.invoke(MockInvocationHandler.java:29)
	at org.easymock.internal.ObjectMethodsFilter.invoke(ObjectMethodsFilter.java:45)
	at $Proxy6.write(Unknown Source)
	at logging.Log._filter(Log.java:91)
	at logging.Log.info(Log.java:54)
	at logging.LoggerTest.testLoggerFiltering2(LoggerTest.java:92)

Testcase: testLoggerClose took 0 sec
